name: Build and Push Image to ACR with OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project to Ensure Version Extraction Works
        run: |
          mvn clean package -DskipTests

      - name: Get Application Version and Sanitize for DNS
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          SANITIZED_VERSION=$(echo "$VERSION" | tr '.' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-40)  # Truncate to 40 chars
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "DNS_SAFE_VERSION=$SANITIZED_VERSION" >> $GITHUB_ENV

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.AZURE_ACR_NAME }}

      - name: Set up pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.8.8

      - name: Build and Push Image with Buildpacks
        run: |
          pack build ${{ vars.AZURE_ACR_NAME }}.azurecr.io/spring-boot-app:$DNS_SAFE_VERSION \
            --builder paketobuildpacks/builder:full \
            --publish

      - name: Get ACR Credentials
        run: |
          ACR_CREDENTIALS=$(az acr credential show --name ${{ vars.AZURE_ACR_NAME }} --query "{username:username,password:passwords[0].value}" --output json)
          echo "ACR_USERNAME=$(echo $ACR_CREDENTIALS | jq -r '.username')" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(echo $ACR_CREDENTIALS | jq -r '.password')" >> $GITHUB_ENV

      - name: Deploy New ACI with Versioned Image
        run: |
          az container create --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --name ${{ vars.AZURE_ACI_NAME }} \
            --image ${{ vars.AZURE_ACR_NAME }}.azurecr.io/spring-boot-app:$DNS_SAFE_VERSION \
            --cpu 1 --memory 2 \
            --dns-name-label xyz-product-service-$DNS_SAFE_VERSION \
            --ports 8080 \
            --ip-address Public \
            --restart-policy Always \
            --assign-identity \
            --registry-login-server ${{ vars.AZURE_ACR_NAME }}.azurecr.io \
            --registry-username $ACR_USERNAME \
            --registry-password $ACR_PASSWORD \
            --os-type Linux
