name: Build and Deploy with Buildpacks

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Pack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/latest/download/pack-linux-amd64.tgz" | tar -xz -C /usr/local/bin

      - name: Build Docker Image with Paketo Buildpacks
        run: |
          pack build myregistry.azurecr.io/myapp:latest --builder paketobuildpacks/builder-jammy-base

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login myregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: docker push myregistry.azurecr.io/myapp:latest
