name: Build and Deploy with Buildpacks

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Pack CLI
        run: |
          PACK_VERSION=$(curl -sSL https://api.github.com/repos/buildpacks/pack/releases/latest | jq -r .tag_name)
          curl -sSL "https://github.com/buildpacks/pack/releases/download/${PACK_VERSION}/pack-linux-amd64.tgz" | tar -xz -C /usr/local/bin

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry via OIDC
        run: |
          TOKEN=$(az acr login --name myregistry --expose-token --output tsv --query accessToken)
          echo $TOKEN | docker login myregistry.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin

      - name: Build Docker Image with Paketo Buildpacks
        run: |
          pack build myregistry.azurecr.io/myapp:latest --builder paketobuildpacks/builder-jammy-base

      - name: Push Docker Image
        run: docker push myregistry.azurecr.io/myapp:latest
