name: Build and Deploy to ACI with OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.AZURE_ACR_NAME }}

      - name: Set up pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.8.8

      - name: Build and Push Image with Buildpacks
        run: |
          pack build ${{ vars.AZURE_ACR_NAME }}.azurecr.io/spring-boot-app:latest \
            --builder paketobuildpacks/builder:full \
            --publish

      - name: Deploy to Azure Container Instances (ACI)
        run: |
          az container create --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --name ${{ vars.AZURE_ACI_NAME }} \
            --image ${{ vars.AZURE_ACR_NAME }}.azurecr.io/spring-boot-app:latest \
            --cpu 1 --memory 2 \
            --dns-name-label spring-boot-service-${{ github.run_id }} \
            --ports 8080 \
            --ip-address Public \
            --restart-policy Always \
            --assign-identity \
            --registry-login-server ${{ vars.AZURE_ACR_NAME }}.azurecr.io \
            --os-type Linux

      - name: Get ACI Managed Identity Principal ID
        id: get_principal_id
        run: |
          PRINCIPAL_ID=$(az container show --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_ACI_NAME }} --query "identity.principalId" --output tsv)
          echo "ACI_PRINCIPAL_ID=$PRINCIPAL_ID" >> $GITHUB_ENV

      - name: Assign AcrPull Role to ACI Managed Identity
        run: |
          az role assignment create --assignee $ACI_PRINCIPAL_ID \
            --scope $(az acr show --name ${{ vars.AZURE_ACR_NAME }} --query id -o tsv) \
            --role AcrPull
