name: Test ACR Connection
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Necessary for Workload Identity Federation

jobs:
  test-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure using Workload Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Test ACR Connection
        run: |
          az acr login --name productserviceacr
          az acr repository list --name productserviceacr --output table

